config/routes.rb
Rails.application.routes.draw do
  root 'propertys#index'
  resources :nearest_stations
  resources :propertys
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/nearest_station.rb
class NearestStation < ApplicationRecord
  belongs_to :property
end

app/models/property.rb
class Property < ApplicationRecord
  has_many :nearest_stations, dependent: :destroy
  accepts_nested_attributes_for :nearest_stations, allow_destroy: true, reject_if: :all_blank
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/nearest_stations_controller.rb
class NearestStationsController < ApplicationController
end

app/controllers/propertys_controller.rb
class PropertysController < ApplicationController
  before_action :set_property, only: [ :show, :edit, :update, :destroy ]

  def new
    if params[:back]
      @property = Property.new(property_params)
    else
      @property = Property.new
      2.times { @property.nearest_stations.build }
    end
  end

  def create
    @property = Property.new(property_params)
    if @property.save
      redirect_to propertys_path, notice: "登録完了"
    else
      render :new
    end
  end

  def update
    if @property.update(property_params)
      redirect_to propertys_path, notice: "編集完了"
    else
      render :new
    end
  end

  def index
    @property = Property.all
  end

  def show
  end

  def edit
    @property.nearest_stations.build
  end

  def destroy
    @property.destroy
    redirect_to propertys_path, notice: "削除完了"
  end

  private

  def property_params
    params.require(:property).permit(:name, :value, :address, :age, :memo, nearest_stations_attributes:[:id, :station, :route, :time])
  end

  def set_property
    @property = Property.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nearest_stations_helper.rb
module NearestStationsHelper
end

app/helpers/propertys_helper.rb
module PropertysHelper
  def choose_path
    if action_name == "new"
      propertys_path
    elsif action_name == "edit"
      property_path
    end
  end
  def choose_request
    if request.patch?
      'patch'
    elsif request.post?
      'post'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevExam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/propertys/_form.html.erb
<%= form_with(model: @property, local: true, url: choose_path, method: choose_request) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= @property.errors.count %> 件のエラーがあります。</h2>
      <ul>
      <% @property.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
  <div class="property_form">
    <%= f.label "物件名" %><br>
    <%= f.text_field :name %><br>
    <%= f.label "賃料" %><br>
    <%= f.text_field :value %><br>
    <%= f.label "住所" %><br>
    <%= f.text_field :address %><br>
    <%= f.label "築年数" %><br>
    <%= f.text_field :age %><br>
    <%= f.label "備考" %><br>
    <%= f.text_area :memo %><br>
  </div>
  <div class="station_form">
    <% n = 0 %>
    <%= f.fields_for :nearest_stations do |near| %>
      <h2>最寄り駅<%= n += 1 %></h2>
      <%= near.label "路線名" %><br>
      <%= near.text_field :route %><br>
      <%= near.label "駅名" %><br>
      <%= near.text_field :station %><br>
      <%= near.label "徒歩分数" %><br>
      <%= near.text_field :time %><br><br>
    <% end %>
  </div>
  <%= f.submit "登録する"%>
<% end %>

app/views/propertys/edit.html.erb
<h1>物件編集</h1></div>

<%= render 'form'%>

<%= link_to '詳細', property_path %> |
<%= link_to '戻る', propertys_path %>

app/views/propertys/index.html.erb
<h1>物件一覧</h1>
<table>
  <thead>
    <tr>
      <th>物件名</th>
      <th>賃料</th>
      <th>住所</th>
      <th>築年数</th>
      <th>備考</th>
    </tr>
  </thead>

  <tbody>
    <% @property.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= property.value.to_s(:delimited) %>円</td>
        <td><%= property.address %></td>
        <td><%= property.age %>年</td>
        <td><%= property.memo %></td>
        <td><%= link_to '詳細', property %></td>
        <td><%= link_to '編集', edit_property_path(property) %></td>
        <td><%= link_to '削除', property, method: :delete, data: { confirm: '本当に消してもいいですか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '物件を登録する', new_property_path %>

app/views/propertys/new.html.erb
<h1>物件登録</h1>

<%= render 'form' %>

<div class="station_form">
  <%= link_to "戻る", propertys_path%>
</div>

app/views/propertys/show.html.erb
<div class="property_form">
  <p>
    <strong>物件名:</strong><%= @property.name %>
  </p>
  <p>
    <strong>賃料:</strong><%= @property.value %>
  </p>
  <p>
    <strong>住所:</strong><%= @property.address %>
  </p>
  <p>
    <strong>築年数:</strong><%= @property.age %>
  </p>
  <p>
    <strong>備考:</strong><%= @property.memo %>
  </p>
</div>
<div class="station_form">
  <% n = 0 %>
  <% @property.nearest_stations.each do |nearest_station| %>
    <h2>最寄り駅<%= n += 1 %></h2>
      <p>
        <strong>路線名:</strong><%= nearest_station.route %>
      </p>
      <p>
        <strong>駅名:</strong><%= nearest_station.station %>
      </p>
      <p>
        <strong>徒歩分数:</strong><%= nearest_station.time %>分
      </p>


<% end %>
</div>
<%= link_to '編集', edit_property_path %> |
<%= link_to '戻る', propertys_path %>